# Generated by Django 4.2.9 on 2025-01-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("employeeid", models.CharField(max_length=15, unique=True)),
                ("employeename", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=30)),
                ("phonenumber", models.BigIntegerField()),
                ("address", models.CharField(max_length=200)),
                ("jobtitle", models.CharField(max_length=100)),
                ("joiningdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Leaves",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("fromdate", models.DateField()),
                ("todate", models.DateField()),
                ("reason", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=750)),
                ("status", models.IntegerField()),
                (
                    "employeeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendanceApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "day_status",
                    models.CharField(
                        choices=[
                            ("Working", "Working Day"),
                            ("Holiday", "Holiday"),
                            ("Weekend", "Weekend"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Active"), (False, "Not Active")], default=True
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employeeid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendanceApp.employee",
                    ),
                ),
            ],
        ),
    ]
