# Generated by Django 4.2.9 on 2025-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
